{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_jIRA", "rerun": "0"}, "1": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002AC449221A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58333): Max retries exceeded with url: /session/1a697ddf662dbda6efd036d32607d199/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AC449221A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_jira2", "rerun": "0"}}, "suite_name": "test_jIRA.py"}}}, "date": "May 29, 2023", "start_time": 1685378565.7156644, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}